version: "3"
services:
  homepage_nodejs:
    container_name: homepage_nodejs
    build:
        context: ./
        dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"

