version: "3"
services:
  homepage-nodejs:
    container_name: homepage-nodejs
    build:
        context: ./
        dockerfile: ./docker/web/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"

