FROM node:22

RUN apt-get update && apt-get install --no-install-recommends --yes \
  python3.11 \
  python3.11-venv \
  pandoc \
  texlive-latex-base \
  texlive-latex-recommended \
  texlive-latex-extra \
  texlive-fonts-recommended \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /usr/share/doc/* /usr/share/man/*

